"""empty message

Revision ID: b8dcb779ae22
Revises: a74d8733d7ce
Create Date: 2023-04-20 10:10:41.926362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8dcb779ae22'
down_revision = 'a74d8733d7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=False))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
